# Generated by Django 5.2.17 on 2026-09-17 22:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("shop", "0003_orderitem_variant_orderitem_variant_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage off"),
                            ("fixed", "Amount off"),
                            ("free_shipping", "Free shipping"),
                        ],
                        default="percent",
                        max_length=14,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percent for percentage codes, dollars for fixed codes.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "minimum_subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total redemptions allowed. Blank for unlimited.",
                        null=True,
                    ),
                ),
                ("max_uses_per_customer", models.PositiveIntegerField(default=1)),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "excludes_livestock",
                    models.BooleanField(
                        default=False, help_text="Apply only to dry goods lines."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RewardsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_per_dollar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Points earned per dollar of merchandise.",
                        max_digits=6,
                    ),
                ),
                (
                    "cents_per_point",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.05"),
                        help_text="Redemption value of one point, in dollars (0.05 = 20 points per $1).",
                        max_digits=6,
                    ),
                ),
                (
                    "expiry_days",
                    models.PositiveIntegerField(
                        default=180,
                        help_text="Days until earned points expire. 0 disables expiry.",
                    ),
                ),
                (
                    "minimum_redemption",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Fewest points that can be spent at once.",
                    ),
                ),
                (
                    "redeemable_during_sales",
                    models.BooleanField(
                        default=False,
                        help_text="Allow point redemption while a live or flash sale is running.",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "rewards settings",
                "verbose_name_plural": "rewards settings",
            },
        ),
        migrations.CreateModel(
            name="DiscountRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="rewards.discountcode",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_redemptions",
                        to="accounts.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_redemptions",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=24, unique=True)),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("message", models.CharField(blank=True, max_length=240)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_cards",
                        to="accounts.customer",
                    ),
                ),
                (
                    "purchased_with_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_gift_cards",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftCardTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Negative when spent.",
                        max_digits=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gift_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="rewards.giftcard",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_card_transactions",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("earned", "Earned"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("adjustment", "Manual adjustment"),
                            ("refunded", "Returned from a cancelled order"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Positive to credit, negative to debit."
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="accounts.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_transactions",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
