# Generated by Django 5.2.17 on 2026-09-17 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the order was placed by a signed-in account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_orders",
                to="accounts.customer",
            ),
        ),
    ]
