# Generated by Django 5.2.17 on 2026-09-17 20:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="collections/")),
                ("show_on_homepage", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("coral", "Coral"),
                            ("fish", "Fish"),
                            ("invertebrate", "Invertebrate"),
                            ("dry_goods", "Dry goods"),
                        ],
                        default="coral",
                        help_text="Drives which care fields show on products in this category.",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="categories/")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "show_in_nav",
                    models.BooleanField(
                        default=True,
                        help_text="Show this category in the main storefront menu.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for a top-level department.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("sku", models.CharField(blank=True, max_length=40, unique=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("coral", "Coral"),
                            ("fish", "Fish"),
                            ("invertebrate", "Invertebrate"),
                            ("dry_goods", "Dry goods"),
                        ],
                        default="coral",
                        max_length=20,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="One line shown under the title.",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("scientific_name", models.CharField(blank=True, max_length=160)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price. Set above the price to show a sale badge.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_wysiwyg",
                    models.BooleanField(
                        default=False,
                        help_text="What-you-see-is-what-you-get: this exact colony, quantity of one.",
                        verbose_name="WYSIWYG",
                    ),
                ),
                ("track_inventory", models.BooleanField(default=True)),
                ("stock_quantity", models.IntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=2)),
                (
                    "care_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lighting",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "flow",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bottom", "Bottom / sand bed"),
                            ("middle", "Mid rock"),
                            ("top", "Upper rock"),
                            ("any", "Anywhere"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "temperament",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("peaceful", "Peaceful"),
                            ("semi", "Semi-aggressive"),
                            ("aggressive", "Aggressive"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "reef_safe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Reef safe"),
                            ("caution", "Reef safe with caution"),
                            ("no", "Not reef safe"),
                        ],
                        max_length=10,
                    ),
                ),
                ("diet", models.CharField(blank=True, max_length=160)),
                (
                    "max_size",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "4 inches" or "Colony to 12in"',
                        max_length=60,
                    ),
                ),
                (
                    "min_tank_size_gallons",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "is_aquacultured",
                    models.BooleanField(
                        default=False,
                        help_text="Grown in-house or by a partner farm rather than wild.",
                    ),
                ),
                ("is_captive_bred", models.BooleanField(default=False)),
                (
                    "requires_overnight_shipping",
                    models.BooleanField(
                        default=False,
                        help_text="Livestock: forces overnight shipping and the live arrival guarantee.",
                    ),
                ),
                ("acclimation_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text='Optional ribbon, e.g. "Limited" or "New"',
                        max_length=30,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="catalog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("collection", "product")},
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="catalog.CollectionItem",
                to="catalog.product",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Photographed under 20k Radion"',
                        max_length=160,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "sort_order", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "published_at"], name="catalog_pro_status_4a4a51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_type"], name="catalog_pro_product_9ecdd3_idx"
            ),
        ),
    ]
