# Generated by Django 5.2.17 on 2026-09-17 22:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bundle_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many pieces a frag pack contains, when it is a bundle.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_mystery",
            field=models.BooleanField(
                default=False,
                help_text="Bundle whose exact contents are a surprise (mystery box).",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("coral", "Coral"),
                    ("fish", "Fish"),
                    ("invertebrate", "Invertebrate"),
                    ("dry_goods", "Dry goods"),
                    ("bundle", "Frag pack / bundle"),
                ],
                default="coral",
                help_text="Drives which care fields show on products in this category.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("coral", "Coral"),
                    ("fish", "Fish"),
                    ("invertebrate", "Invertebrate"),
                    ("dry_goods", "Dry goods"),
                    ("bundle", "Frag pack / bundle"),
                ],
                default="coral",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=140)),
                (
                    "url",
                    models.URLField(help_text="YouTube, Vimeo or a direct MP4 link."),
                ),
                ("thumbnail", models.ImageField(blank=True, upload_to="videos/")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="BundleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "bundle",
                    models.ForeignKey(
                        limit_choices_to={"product_type": "bundle"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_bundles",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
                "unique_together": {("bundle", "product")},
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "Single frag", "Mini colony", "10 pack"',
                        max_length=80,
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=48, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                ("track_inventory", models.BooleanField(default=True)),
                (
                    "pack_quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many animals or items this option contains.",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "price"],
                "unique_together": {("product", "name")},
            },
        ),
    ]
