# Generated by Django 5.2.17 on 2026-09-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=160)),
                ("message", models.TextField()),
                ("order_reference", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_handled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping & arrival"),
                            ("livestock", "Livestock care"),
                            ("orders", "Orders & returns"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("question", models.CharField(max_length=240)),
                ("answer", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ item",
                "ordering": ["topic", "sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=60)),
                ("headline", models.CharField(max_length=120)),
                ("subhead", models.CharField(blank=True, max_length=240)),
                ("image", models.ImageField(blank=True, upload_to="hero/")),
                (
                    "cta_label",
                    models.CharField(blank=True, default="Shop corals", max_length=40),
                ),
                (
                    "cta_url",
                    models.CharField(blank=True, default="/shop/", max_length=300),
                ),
                ("secondary_cta_label", models.CharField(blank=True, max_length=40)),
                ("secondary_cta_url", models.CharField(blank=True, max_length=300)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("summary", models.CharField(blank=True, max_length=240)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Blank lines start a new paragraph. Basic HTML is allowed.",
                    ),
                ),
                ("hero_image", models.ImageField(blank=True, upload_to="pages/")),
                ("show_in_header", models.BooleanField(default=False)),
                ("show_in_footer", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=160)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="Reef & Rift", max_length=80)),
                (
                    "tagline",
                    models.CharField(
                        default="Aquacultured corals, shipped overnight.",
                        max_length=160,
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="branding/")),
                (
                    "contact_email",
                    models.EmailField(
                        default="hello@reefandrift.example", max_length=254
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("address", models.TextField(blank=True)),
                (
                    "hours",
                    models.CharField(
                        blank=True, help_text='e.g. "Tue-Sat 11am-6pm"', max_length=160
                    ),
                ),
                ("announcement_enabled", models.BooleanField(default=True)),
                (
                    "announcement_text",
                    models.CharField(
                        blank=True,
                        default="Free overnight shipping on orders $299+",
                        max_length=200,
                    ),
                ),
                ("announcement_url", models.CharField(blank=True, max_length=300)),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=299,
                        help_text="Order subtotal at which livestock shipping becomes free. 0 disables.",
                        max_digits=8,
                    ),
                ),
                (
                    "livestock_shipping_rate",
                    models.DecimalField(decimal_places=2, default=59, max_digits=8),
                ),
                (
                    "drygoods_shipping_rate",
                    models.DecimalField(decimal_places=2, default=12, max_digits=8),
                ),
                (
                    "tax_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Applied to the subtotal.",
                        max_digits=5,
                    ),
                ),
                (
                    "shipping_days",
                    models.CharField(
                        default="Monday, Tuesday and Wednesday",
                        help_text="Days livestock leaves the facility.",
                        max_length=120,
                    ),
                ),
                (
                    "guarantee_headline",
                    models.CharField(default="Live Arrival Guarantee", max_length=120),
                ),
                (
                    "guarantee_blurb",
                    models.CharField(
                        default="Every animal ships overnight in an insulated box and is covered for 8 hours after delivery.",
                        max_length=240,
                    ),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                (
                    "footer_note",
                    models.CharField(
                        blank=True,
                        default="Reef responsibly. Buy aquacultured.",
                        max_length=240,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("author", models.CharField(max_length=80)),
                ("location", models.CharField(blank=True, max_length=80)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("featured", "Featured products"),
                            ("new_arrivals", "Newest arrivals"),
                            ("wysiwyg", "WYSIWYG picks"),
                            ("on_sale", "On sale"),
                            ("collection", "Specific collection"),
                            ("category_grid", "Category grid"),
                            ("rich_text", "Rich text band"),
                            ("guarantee", "Guarantee / trust bar"),
                            ("testimonials", "Testimonials"),
                        ],
                        max_length=20,
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=120)),
                ("subheading", models.CharField(blank=True, max_length=240)),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Used by the rich text band."
                    ),
                ),
                ("cta_label", models.CharField(blank=True, max_length=40)),
                ("cta_url", models.CharField(blank=True, max_length=300)),
                ("max_items", models.PositiveIntegerField(default=8)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when the kind is 'Specific collection'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homepage_sections",
                        to="catalog.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "homepage section",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="LiveSaleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="events/")),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stream_url",
                    models.URLField(
                        blank=True, help_text="YouTube / Instagram live link."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_sales",
                        to="catalog.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="NavigationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=60)),
                ("url", models.CharField(blank=True, max_length=300)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("footer_shop", "Footer - Shop"),
                            ("footer_support", "Footer - Support"),
                        ],
                        default="header",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a CMS page instead of typing a URL.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_links",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "ordering": ["placement", "sort_order", "pk"],
            },
        ),
    ]
