# Generated by Django 5.2.17 on 2026-09-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="allow_order_additions",
            field=models.BooleanField(
                default=True,
                help_text="Let customers add live sale wins to an unshipped order without paying shipping twice.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shipping_cutoff_time",
            field=models.TimeField(
                default="14:00",
                help_text="Orders placed before this local time ship the same business day.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shipping_weekdays",
            field=models.CharField(
                default="0,1,2",
                help_text="Weekday numbers livestock ships on (Monday=0). e.g. 0,1,2",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="wholesale_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=30,
                help_text="Percentage off merchandise for approved wholesale accounts.",
                max_digits=5,
            ),
        ),
    ]
