# Generated by Django 5.2.17 on 2026-09-17 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_bundle_size_product_is_mystery_and_more"),
        ("cms", "0002_sitesettings_allow_order_additions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("care", "Care guide"),
                            ("news", "Shop news"),
                            ("species", "Species spotlight"),
                            ("howto", "How-to"),
                        ],
                        default="care",
                        max_length=12,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=300)),
                (
                    "body",
                    models.TextField(
                        help_text="Blank lines start a new paragraph. Basic HTML is allowed."
                    ),
                ),
                ("hero_image", models.ImageField(blank=True, upload_to="articles/")),
                ("author", models.CharField(blank=True, max_length=120)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_products",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="catalog.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
