# Generated by Django 5.2.17 on 2026-09-18 15:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("shop", "0004_order_discount_code_order_discount_total_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("abandoned_cart", "Abandoned cart reminder"),
                            ("back_in_stock", "Back in stock"),
                            ("doa_received", "DOA claim received"),
                            ("doa_resolved", "DOA claim resolved"),
                            ("gift_card_issued", "Gift card issued"),
                            ("order_confirmation", "Order confirmation"),
                            ("order_delivered", "Order delivered (DOA window open)"),
                            ("order_shipped", "Order shipped"),
                            ("payment_received", "Payment received"),
                            ("points_expiring", "Reward points expiring"),
                            ("review_request", "Review request"),
                            ("welcome", "Welcome (new account)"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(
                        help_text="Django template syntax. The available variables are listed under each template in the admin."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Turn off to stop sending this email entirely.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AbandonedCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(blank=True, max_length=40, unique=True)),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text="Snapshot of the cart when it was last seen.",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("contains_wysiwyg", models.BooleanField(default=False)),
                ("reminders_sent", models.PositiveIntegerField(default=0)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abandoned_carts",
                        to="accounts.customer",
                    ),
                ),
                (
                    "placed_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovered_from_carts",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "abandoned cart",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (duplicate)"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identifies this exact send, so a retry cannot email twice.",
                        max_length=120,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="accounts.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["key", "recipient"], name="notificatio_key_5e9652_idx"
                    )
                ],
            },
        ),
    ]
